-- ============================================================
-- Skema & Data Database MySQL untuk Whusnet OLT Pro / Web Aktivasi
-- Database : web_aktivasi
-- User     : whusnet_web_aktivasi
-- Password : Strategi*1
-- Host     : localhost
-- ============================================================

CREATE DATABASE IF NOT EXISTS `web_aktivasi` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `web_aktivasi`;

-- ------------------------------------------------------------
-- 1. Tabel OLT Configs
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `olt_configs` (
  `id` VARCHAR(100) NOT NULL,
  `code` TEXT NOT NULL,
  `username` VARCHAR(100) DEFAULT '',
  `password` VARCHAR(100) DEFAULT '',
  `subtabs` JSON,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------------
-- 2. Tabel Templates
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `templates` (
  `name` VARCHAR(100) NOT NULL,
  `body` MEDIUMTEXT NOT NULL,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------------
-- 3. Tabel Shortcuts
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `shortcuts` (
  `name` VARCHAR(100) NOT NULL,
  `body` MEDIUMTEXT NOT NULL,
  `category` VARCHAR(100) NOT NULL DEFAULT 'ZTE C320',
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------------
-- 4. Tabel Speed Profiles
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `speed_profiles` (
  `name` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------------
-- 5. Tabel Users
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `id` VARCHAR(100) NOT NULL,
  `username` VARCHAR(100) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `role` VARCHAR(50) NOT NULL DEFAULT 'operator',
  `createdAt` VARCHAR(50),
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_username` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- SEED DATA BAWAAN / INITIAL DATA
-- ============================================================

-- Data OLT Configs
INSERT INTO `olt_configs` (`id`, `code`, `username`, `password`, `subtabs`) VALUES ('A1-NGAMPEL-DYG', 'A1-NGPL-DYG - 10.123.123.15', 'wholtgnrt', 'whusnet#123', '{\"D1A\":{\"vlan\":1010,\"ppp_prefix\":\"A1X1A\",\"ip_olt\":\"10.123.123.15\",\"vlanProfile\":\"PPPoE1010\",\"speedProfile\":\"\",\"template\":\"STANDAR\"},\"D1C\":{\"vlan\":1012,\"ppp_prefix\":\"A1X1C\",\"ip_olt\":\"10.123.123.15\",\"vlanProfile\":\"PPPoE1012\",\"speedProfile\":\"\",\"template\":\"STANDAR\"}}') ON DUPLICATE KEY UPDATE `code`='A1-NGPL-DYG - 10.123.123.15', `username`='wholtgnrt', `password`='whusnet#123', `subtabs`='{\"D1A\":{\"vlan\":1010,\"ppp_prefix\":\"A1X1A\",\"ip_olt\":\"10.123.123.15\",\"vlanProfile\":\"PPPoE1010\",\"speedProfile\":\"\",\"template\":\"STANDAR\"},\"D1C\":{\"vlan\":1012,\"ppp_prefix\":\"A1X1C\",\"ip_olt\":\"10.123.123.15\",\"vlanProfile\":\"PPPoE1012\",\"speedProfile\":\"\",\"template\":\"STANDAR\"}}';
INSERT INTO `olt_configs` (`id`, `code`, `username`, `password`, `subtabs`) VALUES ('A2-NGAMPEL-PNKL', 'A2-NGPL-PNKL - 10.123.123.16', '', '', '{}') ON DUPLICATE KEY UPDATE `code`='A2-NGPL-PNKL - 10.123.123.16', `username`='', `password`='', `subtabs`='{}';
INSERT INTO `olt_configs` (`id`, `code`, `username`, `password`, `subtabs`) VALUES ('A3-NGAMPEL-KTN', 'A3-NGPL-KTN - 10.123.123.155', 'wholtgnrt', 'whusnet#123', '{\"D1E\":{\"vlan\":1014,\"ppp_prefix\":\"A3X1E\",\"ip_olt\":\"10.123.123.155\",\"vlanProfile\":\"PPPoE1014\",\"speedProfile\":\"\",\"template\":\"STANDAR\"}}') ON DUPLICATE KEY UPDATE `code`='A3-NGPL-KTN - 10.123.123.155', `username`='wholtgnrt', `password`='whusnet#123', `subtabs`='{\"D1E\":{\"vlan\":1014,\"ppp_prefix\":\"A3X1E\",\"ip_olt\":\"10.123.123.155\",\"vlanProfile\":\"PPPoE1014\",\"speedProfile\":\"\",\"template\":\"STANDAR\"}}';
INSERT INTO `olt_configs` (`id`, `code`, `username`, `password`, `subtabs`) VALUES ('B1-SUMBEREJO-SBR', 'B1-SBR-SBR - 10.123.123.35', 'wholtgnrt', 'whusnet#123', '{\"D3A\":{\"vlan\":1032,\"ppp_prefix\":\"B1X3A\",\"ip_olt\":\"10.123.123.35\",\"vlanProfile\":\"PPPoE1032\",\"speedProfile\":\"\",\"template\":\"STANDAR\"},\"D3B\":{\"vlan\":1031,\"ppp_prefix\":\"B1X3B\",\"ip_olt\":\"10.123.123.35\",\"vlanProfile\":\"PPPoE1031\",\"speedProfile\":\"\",\"template\":\"STANDAR\"},\"D3C\":{\"vlan\":1030,\"ppp_prefix\":\"B1X3C\",\"ip_olt\":\"10.123.123.35\",\"vlanProfile\":\"PPPoE1030\",\"speedProfile\":\"\",\"template\":\"STANDAR\"},\"D3D\":{\"vlan\":1033,\"ppp_prefix\":\"B1X3D\",\"ip_olt\":\"10.123.123.35\",\"vlanProfile\":\"PPPoE1033\",\"speedProfile\":\"\",\"template\":\"STANDAR\"}}') ON DUPLICATE KEY UPDATE `code`='B1-SBR-SBR - 10.123.123.35', `username`='wholtgnrt', `password`='whusnet#123', `subtabs`='{\"D3A\":{\"vlan\":1032,\"ppp_prefix\":\"B1X3A\",\"ip_olt\":\"10.123.123.35\",\"vlanProfile\":\"PPPoE1032\",\"speedProfile\":\"\",\"template\":\"STANDAR\"},\"D3B\":{\"vlan\":1031,\"ppp_prefix\":\"B1X3B\",\"ip_olt\":\"10.123.123.35\",\"vlanProfile\":\"PPPoE1031\",\"speedProfile\":\"\",\"template\":\"STANDAR\"},\"D3C\":{\"vlan\":1030,\"ppp_prefix\":\"B1X3C\",\"ip_olt\":\"10.123.123.35\",\"vlanProfile\":\"PPPoE1030\",\"speedProfile\":\"\",\"template\":\"STANDAR\"},\"D3D\":{\"vlan\":1033,\"ppp_prefix\":\"B1X3D\",\"ip_olt\":\"10.123.123.35\",\"vlanProfile\":\"PPPoE1033\",\"speedProfile\":\"\",\"template\":\"STANDAR\"}}';
INSERT INTO `olt_configs` (`id`, `code`, `username`, `password`, `subtabs`) VALUES ('C1-JETIS-JTS', 'C1-JTS-JTS - 10.123.123.45', 'wholtgnrt', 'whusnet#123', '{\"D4A\":{\"vlan\":1042,\"ppp_prefix\":\"C1X4A\",\"ip_olt\":\"10.123.123.45\",\"vlanProfile\":\"PPPoE1042\",\"speedProfile\":\"\",\"template\":\"STANDAR\"},\"D4B\":{\"vlan\":1041,\"ppp_prefix\":\"C1X4B\",\"ip_olt\":\"10.123.123.45\",\"vlanProfile\":\"PPPoE1041\",\"speedProfile\":\"\",\"template\":\"STANDAR\"},\"D4C\":{\"vlan\":1040,\"ppp_prefix\":\"C1X4C\",\"ip_olt\":\"10.123.123.45\",\"vlanProfile\":\"PPPoE1040\",\"speedProfile\":\"\",\"template\":\"STANDAR\"},\"D4D\":{\"vlan\":1043,\"ppp_prefix\":\"C1X4D\",\"ip_olt\":\"10.123.123.45\",\"vlanProfile\":\"PPPoE1043\",\"speedProfile\":\"\",\"template\":\"STANDAR\"}}') ON DUPLICATE KEY UPDATE `code`='C1-JTS-JTS - 10.123.123.45', `username`='wholtgnrt', `password`='whusnet#123', `subtabs`='{\"D4A\":{\"vlan\":1042,\"ppp_prefix\":\"C1X4A\",\"ip_olt\":\"10.123.123.45\",\"vlanProfile\":\"PPPoE1042\",\"speedProfile\":\"\",\"template\":\"STANDAR\"},\"D4B\":{\"vlan\":1041,\"ppp_prefix\":\"C1X4B\",\"ip_olt\":\"10.123.123.45\",\"vlanProfile\":\"PPPoE1041\",\"speedProfile\":\"\",\"template\":\"STANDAR\"},\"D4C\":{\"vlan\":1040,\"ppp_prefix\":\"C1X4C\",\"ip_olt\":\"10.123.123.45\",\"vlanProfile\":\"PPPoE1040\",\"speedProfile\":\"\",\"template\":\"STANDAR\"},\"D4D\":{\"vlan\":1043,\"ppp_prefix\":\"C1X4D\",\"ip_olt\":\"10.123.123.45\",\"vlanProfile\":\"PPPoE1043\",\"speedProfile\":\"\",\"template\":\"STANDAR\"}}';
INSERT INTO `olt_configs` (`id`, `code`, `username`, `password`, `subtabs`) VALUES ('D1-SIMAN-PBSN', 'D1-SMN-PBSN - 10.10.55.2', 'wholtgnrt', 'whusnet#123', '{\"D6A\":{\"vlan\":1060,\"ppp_prefix\":\"D1X6A\",\"ip_olt\":\"10.10.55.2\",\"vlanProfile\":\"PPPoE1060\",\"speedProfile\":\"\",\"template\":\"STANDAR\"},\"D6B\":{\"vlan\":1061,\"ppp_prefix\":\"D1X6B\",\"ip_olt\":\"10.10.55.2\",\"vlanProfile\":\"PPPoE1061\",\"speedProfile\":\"\",\"template\":\"STANDAR\"}}') ON DUPLICATE KEY UPDATE `code`='D1-SMN-PBSN - 10.10.55.2', `username`='wholtgnrt', `password`='whusnet#123', `subtabs`='{\"D6A\":{\"vlan\":1060,\"ppp_prefix\":\"D1X6A\",\"ip_olt\":\"10.10.55.2\",\"vlanProfile\":\"PPPoE1060\",\"speedProfile\":\"\",\"template\":\"STANDAR\"},\"D6B\":{\"vlan\":1061,\"ppp_prefix\":\"D1X6B\",\"ip_olt\":\"10.10.55.2\",\"vlanProfile\":\"PPPoE1061\",\"speedProfile\":\"\",\"template\":\"STANDAR\"}}';
INSERT INTO `olt_configs` (`id`, `code`, `username`, `password`, `subtabs`) VALUES ('E1-SLAHUNG-SLH', 'E1-SLH-SLH - 10.123.123.75', 'wholtgnrt', 'whusnet#123', '{\"D7A\":{\"vlan\":1070,\"ppp_prefix\":\"E1X7A\",\"ip_olt\":\"10.123.123.75\",\"vlanProfile\":\"PPPoE1070\",\"speedProfile\":\"\",\"template\":\"STANDAR\"},\"D7B\":{\"vlan\":1071,\"ppp_prefix\":\"E1X7B\",\"ip_olt\":\"10.123.123.75\",\"vlanProfile\":\"PPPoE1071\",\"speedProfile\":\"\",\"template\":\"STANDAR\"}}') ON DUPLICATE KEY UPDATE `code`='E1-SLH-SLH - 10.123.123.75', `username`='wholtgnrt', `password`='whusnet#123', `subtabs`='{\"D7A\":{\"vlan\":1070,\"ppp_prefix\":\"E1X7A\",\"ip_olt\":\"10.123.123.75\",\"vlanProfile\":\"PPPoE1070\",\"speedProfile\":\"\",\"template\":\"STANDAR\"},\"D7B\":{\"vlan\":1071,\"ppp_prefix\":\"E1X7B\",\"ip_olt\":\"10.123.123.75\",\"vlanProfile\":\"PPPoE1071\",\"speedProfile\":\"\",\"template\":\"STANDAR\"}}';
INSERT INTO `olt_configs` (`id`, `code`, `username`, `password`, `subtabs`) VALUES ('F1-TEMON-SNRG', 'F1-TMN-SNRG - 10.123.123.55', '', '', '{}') ON DUPLICATE KEY UPDATE `code`='F1-TMN-SNRG - 10.123.123.55', `username`='', `password`='', `subtabs`='{}';
INSERT INTO `olt_configs` (`id`, `code`, `username`, `password`, `subtabs`) VALUES ('F2-TEMON-SNRG', 'F2-TMN-SNRG - 10.123.123.56', '', '', '{}') ON DUPLICATE KEY UPDATE `code`='F2-TMN-SNRG - 10.123.123.56', `username`='', `password`='', `subtabs`='{}';
INSERT INTO `olt_configs` (`id`, `code`, `username`, `password`, `subtabs`) VALUES ('G1-SAMBIT-BDG', 'G1-SMBT-BDG - 10.10.99.3', '', '', '{}') ON DUPLICATE KEY UPDATE `code`='G1-SMBT-BDG - 10.10.99.3', `username`='', `password`='', `subtabs`='{}';
INSERT INTO `olt_configs` (`id`, `code`, `username`, `password`, `subtabs`) VALUES ('H1-PACITAN-PLS', 'H1-PCT-PLS - 10.10.88.2', '', '', '{}') ON DUPLICATE KEY UPDATE `code`='H1-PCT-PLS - 10.10.88.2', `username`='', `password`='', `subtabs`='{}';
INSERT INTO `olt_configs` (`id`, `code`, `username`, `password`, `subtabs`) VALUES ('H2-PACITAN-GMH', 'H2-PCT-GMH - 10.10.111.2', 'wholtgnrt', 'whusnet#123', '{\"D8B\":{\"vlan\":1100,\"ppp_prefix\":\"H2X8B\",\"ip_olt\":\"10.10.111.2\",\"vlanProfile\":\"PPPoE1100\",\"speedProfile\":\"\",\"template\":\"STANDAR\"}}') ON DUPLICATE KEY UPDATE `code`='H2-PCT-GMH - 10.10.111.2', `username`='wholtgnrt', `password`='whusnet#123', `subtabs`='{\"D8B\":{\"vlan\":1100,\"ppp_prefix\":\"H2X8B\",\"ip_olt\":\"10.10.111.2\",\"vlanProfile\":\"PPPoE1100\",\"speedProfile\":\"\",\"template\":\"STANDAR\"}}';
INSERT INTO `olt_configs` (`id`, `code`, `username`, `password`, `subtabs`) VALUES ('H3-PACITAN-PCO', 'H3-PCT-PCO - 10.10.112.2', '', '', '{}') ON DUPLICATE KEY UPDATE `code`='H3-PCT-PCO - 10.10.112.2', `username`='', `password`='', `subtabs`='{}';
INSERT INTO `olt_configs` (`id`, `code`, `username`, `password`, `subtabs`) VALUES ('H4-PACITAN-TGO', 'H4-PCT-TGO - 10.10.114.2', '', '', '{}') ON DUPLICATE KEY UPDATE `code`='H4-PCT-TGO - 10.10.114.2', `username`='', `password`='', `subtabs`='{}';
INSERT INTO `olt_configs` (`id`, `code`, `username`, `password`, `subtabs`) VALUES ('I1-CARUBAN-PLKC', 'I1-CRB-PLKC - 10.123.123.135', 'wholtgnrt', 'whusnet#123', '{\"D13A\":{\"vlan\":1130,\"ppp_prefix\":\"I1X13A\",\"ip_olt\":\"10.123.123.135\",\"vlanProfile\":\"vlan1130\",\"speedProfile\":\"\",\"template\":\"STANDAR\"}}') ON DUPLICATE KEY UPDATE `code`='I1-CRB-PLKC - 10.123.123.135', `username`='wholtgnrt', `password`='whusnet#123', `subtabs`='{\"D13A\":{\"vlan\":1130,\"ppp_prefix\":\"I1X13A\",\"ip_olt\":\"10.123.123.135\",\"vlanProfile\":\"vlan1130\",\"speedProfile\":\"\",\"template\":\"STANDAR\"}}';
INSERT INTO `olt_configs` (`id`, `code`, `username`, `password`, `subtabs`) VALUES ('SANDYA-SMN', 'SANDYA-SMN - 10.10.55.2', 'wholtgnrt', 'whusnet#123', '{\"VLAN-168\":{\"vlan\":168,\"ppp_prefix\":\"J1X\",\"ip_olt\":\"10.10.55.2\",\"vlanProfile\":\"\",\"speedProfile\":\"\",\"template\":\"SANDYA\"},\"VLAN-170\":{\"vlan\":170,\"ppp_prefix\":\"J1X\",\"ip_olt\":\"10.10.55.2\",\"vlanProfile\":\"\",\"speedProfile\":\"\",\"template\":\"SANDYA\"},\"VLAN-803\":{\"vlan\":803,\"ppp_prefix\":\"J1X\",\"ip_olt\":\"10.10.55.2\",\"vlanProfile\":\"\",\"speedProfile\":\"\",\"template\":\"SANDYA\"}}') ON DUPLICATE KEY UPDATE `code`='SANDYA-SMN - 10.10.55.2', `username`='wholtgnrt', `password`='whusnet#123', `subtabs`='{\"VLAN-168\":{\"vlan\":168,\"ppp_prefix\":\"J1X\",\"ip_olt\":\"10.10.55.2\",\"vlanProfile\":\"\",\"speedProfile\":\"\",\"template\":\"SANDYA\"},\"VLAN-170\":{\"vlan\":170,\"ppp_prefix\":\"J1X\",\"ip_olt\":\"10.10.55.2\",\"vlanProfile\":\"\",\"speedProfile\":\"\",\"template\":\"SANDYA\"},\"VLAN-803\":{\"vlan\":803,\"ppp_prefix\":\"J1X\",\"ip_olt\":\"10.10.55.2\",\"vlanProfile\":\"\",\"speedProfile\":\"\",\"template\":\"SANDYA\"}}';
INSERT INTO `olt_configs` (`id`, `code`, `username`, `password`, `subtabs`) VALUES ('SANDYA-KTN', 'SANDYA-KTN - 10.123.123.155', 'wholtgnrt', 'whusnet#123', '{\"VLAN-168\":{\"vlan\":168,\"ppp_prefix\":\"J1X\",\"ip_olt\":\"10.123.123.155\",\"vlanProfile\":\"\",\"speedProfile\":\"\",\"template\":\"SANDYA\"},\"VLAN-170\":{\"vlan\":170,\"ppp_prefix\":\"J1X\",\"ip_olt\":\"10.123.123.155\",\"vlanProfile\":\"\",\"speedProfile\":\"\",\"template\":\"SANDYA\"},\"VLAN-803\":{\"vlan\":803,\"ppp_prefix\":\"J1X\",\"ip_olt\":\"10.123.123.155\",\"vlanProfile\":\"\",\"speedProfile\":\"\",\"template\":\"SANDYA\"}}') ON DUPLICATE KEY UPDATE `code`='SANDYA-KTN - 10.123.123.155', `username`='wholtgnrt', `password`='whusnet#123', `subtabs`='{\"VLAN-168\":{\"vlan\":168,\"ppp_prefix\":\"J1X\",\"ip_olt\":\"10.123.123.155\",\"vlanProfile\":\"\",\"speedProfile\":\"\",\"template\":\"SANDYA\"},\"VLAN-170\":{\"vlan\":170,\"ppp_prefix\":\"J1X\",\"ip_olt\":\"10.123.123.155\",\"vlanProfile\":\"\",\"speedProfile\":\"\",\"template\":\"SANDYA\"},\"VLAN-803\":{\"vlan\":803,\"ppp_prefix\":\"J1X\",\"ip_olt\":\"10.123.123.155\",\"vlanProfile\":\"\",\"speedProfile\":\"\",\"template\":\"SANDYA\"}}';
INSERT INTO `olt_configs` (`id`, `code`, `username`, `password`, `subtabs`) VALUES ('SANDYA-JTS', 'SANDYA-JTS - 10.123.123.45', 'wholtgnrt', 'whusnet#123', '{\"VLAN-168\":{\"vlan\":168,\"ppp_prefix\":\"J1X\",\"ip_olt\":\"10.123.123.45\",\"vlanProfile\":\"\",\"speedProfile\":\"\",\"template\":\"SANDYA\"},\"VLAN-170\":{\"vlan\":170,\"ppp_prefix\":\"J1X\",\"ip_olt\":\"10.123.123.45\",\"vlanProfile\":\"\",\"speedProfile\":\"\",\"template\":\"SANDYA\"},\"VLAN-803\":{\"vlan\":803,\"ppp_prefix\":\"J1X\",\"ip_olt\":\"10.123.123.45\",\"vlanProfile\":\"\",\"speedProfile\":\"\",\"template\":\"SANDYA\"}}') ON DUPLICATE KEY UPDATE `code`='SANDYA-JTS - 10.123.123.45', `username`='wholtgnrt', `password`='whusnet#123', `subtabs`='{\"VLAN-168\":{\"vlan\":168,\"ppp_prefix\":\"J1X\",\"ip_olt\":\"10.123.123.45\",\"vlanProfile\":\"\",\"speedProfile\":\"\",\"template\":\"SANDYA\"},\"VLAN-170\":{\"vlan\":170,\"ppp_prefix\":\"J1X\",\"ip_olt\":\"10.123.123.45\",\"vlanProfile\":\"\",\"speedProfile\":\"\",\"template\":\"SANDYA\"},\"VLAN-803\":{\"vlan\":803,\"ppp_prefix\":\"J1X\",\"ip_olt\":\"10.123.123.45\",\"vlanProfile\":\"\",\"speedProfile\":\"\",\"template\":\"SANDYA\"}}';
INSERT INTO `olt_configs` (`id`, `code`, `username`, `password`, `subtabs`) VALUES ('MAZZNET-SMN', 'MAZZNET-SMN - 10.10.55.2', 'wholtgnrt', 'whusnet#123', '{\"VLAN-696\":{\"vlan\":696,\"ppp_prefix\":\"\",\"ip_olt\":\"10.10.55.2\",\"vlanProfile\":\"696-OPENPORTMAZZNET\",\"speedProfile\":\"\",\"template\":\"MAZZNET\"}}') ON DUPLICATE KEY UPDATE `code`='MAZZNET-SMN - 10.10.55.2', `username`='wholtgnrt', `password`='whusnet#123', `subtabs`='{\"VLAN-696\":{\"vlan\":696,\"ppp_prefix\":\"\",\"ip_olt\":\"10.10.55.2\",\"vlanProfile\":\"696-OPENPORTMAZZNET\",\"speedProfile\":\"\",\"template\":\"MAZZNET\"}}';
INSERT INTO `olt_configs` (`id`, `code`, `username`, `password`, `subtabs`) VALUES ('MAZZNET-KTN', 'MAZZNET-KTN - 10.123.123.155', 'wholtgnrt', 'whusnet#123', '{\"VLAN-696\":{\"vlan\":696,\"ppp_prefix\":\"\",\"ip_olt\":\"10.123.123.155\",\"vlanProfile\":\"696-OPENPORTMAZZNET\",\"speedProfile\":\"\",\"template\":\"MAZZNET\"}}') ON DUPLICATE KEY UPDATE `code`='MAZZNET-KTN - 10.123.123.155', `username`='wholtgnrt', `password`='whusnet#123', `subtabs`='{\"VLAN-696\":{\"vlan\":696,\"ppp_prefix\":\"\",\"ip_olt\":\"10.123.123.155\",\"vlanProfile\":\"696-OPENPORTMAZZNET\",\"speedProfile\":\"\",\"template\":\"MAZZNET\"}}';

-- Data Templates
INSERT INTO `templates` (`name`, `body`) VALUES ('STANDAR', 'interface gpon-olt_1/{slot}/{port}\nonu {onu} type ALL sn {sn}\nexit\n\ninterface gpon-onu_1/{slot}/{port}:{onu}\nname {odp}_{pppoe}\ntcont 1 name INET profile {profile}\ngemport 1 name INET tcont 1\ngemport 1 traffic-limit upstream {profile} downstream {profile}\nservice-port 1 vport 1 user-vlan {vlan} vlan {vlan}\nexit\n\npon-onu-mng gpon-onu_1/{slot}/{port}:{onu}\nservice INET gemport 1 vlan {vlan}\n{locks}\n\nfirewall enable level low\nsecurity-mgmt 1 state enable mode forward ingress-type wan protocol web\nwan-ip mode pppoe username {pppoe} password 740874 vlan-profile {vlanProfile} host 1\nwan 1 service internet host 1\nexit\nend\nwr\n') ON DUPLICATE KEY UPDATE `body`='interface gpon-olt_1/{slot}/{port}\nonu {onu} type ALL sn {sn}\nexit\n\ninterface gpon-onu_1/{slot}/{port}:{onu}\nname {odp}_{pppoe}\ntcont 1 name INET profile {profile}\ngemport 1 name INET tcont 1\ngemport 1 traffic-limit upstream {profile} downstream {profile}\nservice-port 1 vport 1 user-vlan {vlan} vlan {vlan}\nexit\n\npon-onu-mng gpon-onu_1/{slot}/{port}:{onu}\nservice INET gemport 1 vlan {vlan}\n{locks}\n\nfirewall enable level low\nsecurity-mgmt 1 state enable mode forward ingress-type wan protocol web\nwan-ip mode pppoe username {pppoe} password 740874 vlan-profile {vlanProfile} host 1\nwan 1 service internet host 1\nexit\nend\nwr\n';
INSERT INTO `templates` (`name`, `body`) VALUES ('SANDYA', 'interface gpon-olt_1/{slot}/{port}\nonu {onu} type ALL sn {sn}\n!\ninterface gpon-onu_1/{slot}/{port}:{onu}\n  name {odp}_{pppoe}\n  description {pppoe}\n  tcont 1 name LLSANDYA profile {profile}\n  gemport 1 name LLSANDYA  tcont 1\n  gemport 1 traffic-limit upstream {profile} downstream {profile}\n  service-port 1 vport 1 user-vlan {vlan} vlan {vlan}\n!\npon-onu-mng gpon-onu_1/{slot}/{port}:{onu}\n  service LLSANDYA gemport 1 vlan {vlan}\n  firewall enable level low anti-hack disable\n  security-mgmt 1 state enable mode forward protocol web \n  wan 1 service internet host 1\n!\nend\nwr\n') ON DUPLICATE KEY UPDATE `body`='interface gpon-olt_1/{slot}/{port}\nonu {onu} type ALL sn {sn}\n!\ninterface gpon-onu_1/{slot}/{port}:{onu}\n  name {odp}_{pppoe}\n  description {pppoe}\n  tcont 1 name LLSANDYA profile {profile}\n  gemport 1 name LLSANDYA  tcont 1\n  gemport 1 traffic-limit upstream {profile} downstream {profile}\n  service-port 1 vport 1 user-vlan {vlan} vlan {vlan}\n!\npon-onu-mng gpon-onu_1/{slot}/{port}:{onu}\n  service LLSANDYA gemport 1 vlan {vlan}\n  firewall enable level low anti-hack disable\n  security-mgmt 1 state enable mode forward protocol web \n  wan 1 service internet host 1\n!\nend\nwr\n';
INSERT INTO `templates` (`name`, `body`) VALUES ('MAZZNET', 'interface gpon-olt_1/{slot}/{port}\nonu {onu} type ALL sn {sn}\n!\ninterface gpon-onu_1/{slot}/{port}:{onu}\nname {odp}_{pppoe}\ndescription {pppoe}\ntcont 1 name LLMAZZNET profile {profile}\ngemport 1 name LLMAZZNET tcont 1\ngemport 1 traffic-limit upstream {profile} downstream {profile}\nservice-port 1 vport 1 user-vlan {vlan} vlan {vlan}\n!\npon-onu-mng gpon-onu_1/{slot}/{port}:{onu}\nservice LLMAZZNET gemport 1 vlan {vlan}\n{locks}\nwan-ip 1 mode pppoe username {pppoe} password 14045 vlan-profile 696-OPENPORTMAZZNET host 1\nfirewall enable level low anti-hack disable\nsecurity-mgmt 1 state enable mode forward protocol web \nwan 1 service internet host 1\n\n!\nend\nwr\n') ON DUPLICATE KEY UPDATE `body`='interface gpon-olt_1/{slot}/{port}\nonu {onu} type ALL sn {sn}\n!\ninterface gpon-onu_1/{slot}/{port}:{onu}\nname {odp}_{pppoe}\ndescription {pppoe}\ntcont 1 name LLMAZZNET profile {profile}\ngemport 1 name LLMAZZNET tcont 1\ngemport 1 traffic-limit upstream {profile} downstream {profile}\nservice-port 1 vport 1 user-vlan {vlan} vlan {vlan}\n!\npon-onu-mng gpon-onu_1/{slot}/{port}:{onu}\nservice LLMAZZNET gemport 1 vlan {vlan}\n{locks}\nwan-ip 1 mode pppoe username {pppoe} password 14045 vlan-profile 696-OPENPORTMAZZNET host 1\nfirewall enable level low anti-hack disable\nsecurity-mgmt 1 state enable mode forward protocol web \nwan 1 service internet host 1\n\n!\nend\nwr\n';

-- Data Shortcuts
INSERT INTO `shortcuts` (`name`, `body`, `category`) VALUES ('onu uncfg', 'show gpon onu uncfg', 'ZTE C320') ON DUPLICATE KEY UPDATE `body`='show gpon onu uncfg', `category`='ZTE C320';
INSERT INTO `shortcuts` (`name`, `body`, `category`) VALUES ('onu kosong', 'terminal length 140\n\n\nshow gpon onu state gpon-olt_1/{slot}/{port}', 'ZTE C320') ON DUPLICATE KEY UPDATE `body`='terminal length 140\n\n\nshow gpon onu state gpon-olt_1/{slot}/{port}', `category`='ZTE C320';
INSERT INTO `shortcuts` (`name`, `body`, `category`) VALUES ('conf t', 'conf t', 'ZTE C320') ON DUPLICATE KEY UPDATE `body`='conf t', `category`='ZTE C320';
INSERT INTO `shortcuts` (`name`, `body`, `category`) VALUES ('end', 'end', 'ZTE C320') ON DUPLICATE KEY UPDATE `body`='end', `category`='ZTE C320';
INSERT INTO `shortcuts` (`name`, `body`, `category`) VALUES ('dbm onu', 'show pon power onu-rx gpon-onu_1/{slot}/{port}:{onu}', 'ZTE C320') ON DUPLICATE KEY UPDATE `body`='show pon power onu-rx gpon-onu_1/{slot}/{port}:{onu}', `category`='ZTE C320';
INSERT INTO `shortcuts` (`name`, `body`, `category`) VALUES ('dbm 1 port', 'terminal length 130\n\n\nshow pon power onu-rx gpon-olt_1/{slot}/{port}', 'ZTE C320') ON DUPLICATE KEY UPDATE `body`='terminal length 130\n\n\nshow pon power onu-rx gpon-olt_1/{slot}/{port}', `category`='ZTE C320';
INSERT INTO `shortcuts` (`name`, `body`, `category`) VALUES ('exit & save', 'end\n\n\nwr', 'ZTE C320') ON DUPLICATE KEY UPDATE `body`='end\n\n\nwr', `category`='ZTE C320';
INSERT INTO `shortcuts` (`name`, `body`, `category`) VALUES ('cur-con onu', 'show running-config interface gpon-onu_1/{slot}/{port}:{onu}\n\n\nshow onu running config gpon-onu_1/{slot}/{port}:{onu}', 'ZTE C320') ON DUPLICATE KEY UPDATE `body`='show running-config interface gpon-onu_1/{slot}/{port}:{onu}\n\n\nshow onu running config gpon-onu_1/{slot}/{port}:{onu}', `category`='ZTE C320';
INSERT INTO `shortcuts` (`name`, `body`, `category`) VALUES ('on-off eth', 'pon-onu-mng gpon-onu_1/{slot}/{port}:{onu}\n\n\n{locks}', 'ZTE C320') ON DUPLICATE KEY UPDATE `body`='pon-onu-mng gpon-onu_1/{slot}/{port}:{onu}\n\n\n{locks}', `category`='ZTE C320';
INSERT INTO `shortcuts` (`name`, `body`, `category`) VALUES ('ganti modem', 'interface gpon-onu_1/{slot}/{port}:{onu}\n\n\nregistration-method sn {sn}', 'ZTE C320') ON DUPLICATE KEY UPDATE `body`='interface gpon-onu_1/{slot}/{port}:{onu}\n\n\nregistration-method sn {sn}', `category`='ZTE C320';
INSERT INTO `shortcuts` (`name`, `body`, `category`) VALUES ('cek onu by SN', 'show gpon onu by sn {sn}', 'ZTE C320') ON DUPLICATE KEY UPDATE `body`='show gpon onu by sn {sn}', `category`='ZTE C320';
INSERT INTO `shortcuts` (`name`, `body`, `category`) VALUES ('status wan-ip', 'show gpon remote-onu wan-ip gpon-onu_1/{slot}/{port}:{onu}', 'ZTE C320') ON DUPLICATE KEY UPDATE `body`='show gpon remote-onu wan-ip gpon-onu_1/{slot}/{port}:{onu}', `category`='ZTE C320';
INSERT INTO `shortcuts` (`name`, `body`, `category`) VALUES ('detail-info', 'terminal length 130\n\n\nshow gpon onu detail-info gpon-onu_1/{slot}/{port}:{onu}', 'ZTE C320') ON DUPLICATE KEY UPDATE `body`='terminal length 130\n\n\nshow gpon onu detail-info gpon-onu_1/{slot}/{port}:{onu}', `category`='ZTE C320';

-- Data Speed Profiles
INSERT IGNORE INTO `speed_profiles` (`name`) VALUES ('INTERNET_10M');
INSERT IGNORE INTO `speed_profiles` (`name`) VALUES ('INTERNET_20M');
INSERT IGNORE INTO `speed_profiles` (`name`) VALUES ('INTERNET_30M');
INSERT IGNORE INTO `speed_profiles` (`name`) VALUES ('INTERNET_50M');
INSERT IGNORE INTO `speed_profiles` (`name`) VALUES ('INTERNET_100M');
INSERT IGNORE INTO `speed_profiles` (`name`) VALUES ('INTERNET_150M');
INSERT IGNORE INTO `speed_profiles` (`name`) VALUES ('INTERNET_200M');

-- Data Akun Pengguna
INSERT INTO `users` (`id`, `username`, `name`, `password`, `role`, `createdAt`) VALUES ('1', 'admin', 'Administrator', 'admin', 'admin', '2026-09-30T00:00:00.000Z') ON DUPLICATE KEY UPDATE `name`='Administrator', `role`='admin';
